# snape.sub

# calculate allele frequencies for Pool-seq DNA reads

container_image = file:///staging/lnell/tany_time.sif

log = logs/01-snape/$(readbase).log
error = logs/01-snape/$(readbase).err
output = logs/01-snape/$(readbase).out

executable = 01-snape.sh
arguments = $(readbase) $(n_adults)

batch_name = "snape"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
requirements = (HasCHTCStaging == true)


## Copying outputs to ResearchDrive:
transfer_output_files = $(readbase)_snape.tar
output_destination = pelican://chtc.wisc.edu/researchdrive/arives/CHTC/snape


request_cpus = 15
request_memory = 20GB
request_disk = 80GB

queue readbase,n_adults from readbases.txt
