# npstat.sub

# calculate population-genetic parameters for Pool-seq samples

# Window length in kb:
win_kb = 10

container_image = file:///staging/lnell/tany_time.sif

log =           logs/02-npstat/$(readbase)_$(win_kb)kb.log
error =         logs/02-npstat/$(readbase)_$(win_kb)kb.err
output =        logs/02-npstat/$(readbase)_$(win_kb)kb.out

executable = 02-npstat.sh
arguments = $(readbase) $(n_adults) $(win_kb)

batch_name =    "npstat"

should_transfer_files =     YES
when_to_transfer_output =   ON_EXIT
requirements =              (HasCHTCStaging == true)


## Copying outputs to ResearchDrive:
transfer_output_files = $(readbase)_npstat_$(win_kb)kb.stat.gz
output_destination = pelican://chtc.wisc.edu/researchdrive/arives/CHTC/npstat


request_cpus =      16
request_memory =    16GB
request_disk =      50GB

queue readbase,n_adults from readbases.txt
