# combine-counts.sub

# combine gSYNC files into three:
# one for all samples, one for time series samples,
# and another for spatial samples

container_image = file:///staging/lnell/tany_time.sif

log = combine-counts.log
error = combine-counts.err
output = combine-counts.out

executable = 04-combine-counts.sh

batch_name = "combine-counts"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
requirements = (HasCHTCStaging == true)

## Copying outputs to ResearchDrive:
transfer_output_files = count_masked_time.tar, count_masked_space.tar, count_masked_all.tar
output_destination = pelican://chtc.wisc.edu/researchdrive/arives/CHTC/snape

request_cpus = 2
request_memory = 4GB
request_disk = 80GB

queue 1
