# fastp.sub

# trim Pool-seq DNA reads

container_image = file:///staging/lnell/tany_time.sif

log = logs/01-fastp/$(readbase).log
error = logs/01-fastp/$(readbase).err
output = logs/01-fastp/$(readbase).out

executable = 01-fastp.sh
arguments = $(readbase)

batch_name = "fastp"

## Specify that HTCondor should transfer files to and from the
##  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

## IMPORTANT! Require execute servers that have access to staging
requirements = (HasCHTCStaging == true)

## Tell HTCondor what amount of compute resources
##  each job will need on the computer where it runs.
request_cpus = 8
request_memory = 16GB
request_disk = 60GB


# Run one instance of this job per line in `readbases.txt`
queue readbase from readbases.txt
