# bwa.sub

# align Pool-seq DNA reads

container_image = file:///staging/lnell/tany_time.sif

log = logs/02-bwa/$(readbase).log
error = logs/02-bwa/$(readbase).err
output = logs/02-bwa/$(readbase).out

executable = 02-bwa.sh
arguments = $(readbase)

batch_name = "bwa"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
requirements = (HasCHTCStaging == true)

request_cpus = 8
request_memory = 16GB
request_disk = 120GB

queue readbase from readbases.txt
