# mpileup.sub

# prep aligned Pool-seq DNA reads and call `samtools mpileup`

container_image = file:///staging/lnell/tany_time.sif

log = logs/03-mpileup/$(readbase).log
error = logs/03-mpileup/$(readbase).err
output = logs/03-mpileup/$(readbase).out

executable = 03-mpileup.sh
arguments = $(readbase)

batch_name = "mpileup"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
requirements = (HasCHTCStaging == true)


## Copying outputs to ResearchDrive:
transfer_output_files = $(readbase)_mpileup.txt.gz, $(readbase)_mpileup.tar.gz
output_destination = pelican://chtc.wisc.edu/researchdrive/arives/CHTC/mpileup


request_cpus = 4
request_memory = 32GB
request_disk = 50GB

queue readbase from readbases.txt
