# ont-pi.sub

# calculating nucleotide diversity and heterozygosity from nanopore reads

container_image = file:///staging/lnell/tany_time.sif

log = ont-pi.log
log = logs/04-ont-pi/ont-pi.log
error = logs/04-ont-pi/ont-pi.err
output = logs/04-ont-pi/ont-pi.out

executable = 04-ont-pi.sh

batch_name = "ont-pi"

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
requirements = (HasCHTCStaging == true)

request_cpus = 32
request_memory = 32GB
request_disk = 100GB

queue
